// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.28.3
// source: resolver.proto

package resolverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ResolverService_Resolve_FullMethodName     = "/nexus.resolver.v1.ResolverService/Resolve"
	ResolverService_ResolveMany_FullMethodName = "/nexus.resolver.v1.ResolverService/ResolveMany"
)

// ResolverServiceClient is the client API for ResolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResolverService translates agent:// URIs into transport endpoints.
type ResolverServiceClient interface {
	// Resolve returns the transport endpoint for a given agent URI.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// ResolveMany resolves a batch of agent URIs in a single request.
	ResolveMany(ctx context.Context, in *ResolveManyRequest, opts ...grpc.CallOption) (*ResolveManyResponse, error)
}

type resolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverServiceClient(cc grpc.ClientConnInterface) ResolverServiceClient {
	return &resolverServiceClient{cc}
}

func (c *resolverServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, ResolverService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverServiceClient) ResolveMany(ctx context.Context, in *ResolveManyRequest, opts ...grpc.CallOption) (*ResolveManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveManyResponse)
	err := c.cc.Invoke(ctx, ResolverService_ResolveMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServiceServer is the server API for ResolverService service.
// All implementations must embed UnimplementedResolverServiceServer
// for forward compatibility
//
// ResolverService translates agent:// URIs into transport endpoints.
type ResolverServiceServer interface {
	// Resolve returns the transport endpoint for a given agent URI.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// ResolveMany resolves a batch of agent URIs in a single request.
	ResolveMany(context.Context, *ResolveManyRequest) (*ResolveManyResponse, error)
	mustEmbedUnimplementedResolverServiceServer()
}

// UnimplementedResolverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResolverServiceServer struct {
}

func (UnimplementedResolverServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedResolverServiceServer) ResolveMany(context.Context, *ResolveManyRequest) (*ResolveManyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveMany not implemented")
}
func (UnimplementedResolverServiceServer) mustEmbedUnimplementedResolverServiceServer() {}

// UnsafeResolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServiceServer will
// result in compilation errors.
type UnsafeResolverServiceServer interface {
	mustEmbedUnimplementedResolverServiceServer()
}

func RegisterResolverServiceServer(s grpc.ServiceRegistrar, srv ResolverServiceServer) {
	s.RegisterService(&ResolverService_ServiceDesc, srv)
}

func _ResolverService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResolverService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResolverService_ResolveMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServiceServer).ResolveMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResolverService_ResolveMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServiceServer).ResolveMany(ctx, req.(*ResolveManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResolverService_ServiceDesc is the grpc.ServiceDesc for ResolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.resolver.v1.ResolverService",
	HandlerType: (*ResolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _ResolverService_Resolve_Handler,
		},
		{
			MethodName: "ResolveMany",
			Handler:    _ResolverService_ResolveMany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolver.proto",
}
